version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - backend
